version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-todo-db
    environment:
      POSTGRES_USER: dacque
      POSTGRES_PASSWORD: IRVb99
      POSTGRES_DB: DB_Docker_RA_TB_QD
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo_network

  php:
    image: php:7.4-apache
    container_name: php-todo-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - todo_network
    depends_on:
      - db

networks:
  todo_network:
    driver: bridge

volumes:
  db_data:
